version: '3'
services:
  instapet-backend:
    restart: unless-stopped
 
    build: .
    command: "npm run start"
    working_dir: "/home/node/instapet"
    environment:
      - NODE_ENV=production
    expose: 
      - "3333"
    ports:
      - "3333:3333"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
     - ./compose.env
    #  - ./.env
     