version: '3'
services:
  instapet-backend:
    build: .
    command: "npm run start"
    working_dir: "/home/node/instapet"
    environment:
      - NODE-ENV=production
    expose: 
      - "3330"
    ports:
      - "3330:3333"